[WIP] Fixes #30950 - Enable SmartProxy Registration module
theforeman/puppet-foreman_proxy pull request #619
Opened 2020-10-01 11:03 UTC by stejskalleos

Waiting for: https://github.com/theforeman/smart-proxy/pull/768
---
PR is part of **Simple & automatic host registration WF**, see:
* [RFC](https://community.theforeman.org/t/rfc-simple-automatic-host-registration-wf/19588)
* [Redmine (this PR)](https://projects.theforeman.org/issues/30950)
* [Redmine (Parent task)](https://projects.theforeman.org/issues/30440)

2020-10-01 11:52 UTC, ekohl requested changes
Please also write in the compatibility section in README.md that users on older versions should disable the module since it doesn't exist.

You may also need to create a template for the settings.

Acceptance tests will fail until it's merged in the smart proxy, but at least the unit tests can pass before that.

2020-10-01 11:52 UTC, ekohl commented on manifests/module/registration.pp
> +  Foreman_proxy::ListenOn $listen_on = $foreman_proxy::registration_listen_on,
These need to exist in `init.pp`

2020-10-05 13:13 UTC, ekohl commented on manifests/init.pp
> +  Foreman_proxy::ListenOn $registration_listen_on = $foreman_proxy::params::registration_listen_on,
If you refer to variables in params, the need to be defined in params.pp as well.

2020-10-13 09:53 UTC, ekohl reviewed
Overall it looks good. Just wondering if we should enforce HTTPS-only for security.

2020-10-13 09:53 UTC, ekohl commented on manifests/params.pp
> +  $registration_listen_on = 'both'
Do we need this to be available on HTTP? Aren't we trying to get HTTPS working to make it secure?

2020-10-13 09:53 UTC, ekohl commented on manifests/module/registration.pp
> +    feature   => 'Registration',
Note to self: confirmed that this matches Foreman's feature name (https://github.com/theforeman/foreman/commit/31b0d198080ca9f1444308f726870f0bf49208ec)

2020-10-23 13:46 UTC, ares commented
After a quick clarification, the pending thing here is to enforce https for this module. Then should be good to go.

2020-10-26 11:25 UTC, ekohl approved these changes

2020-10-26 11:25 UTC, merged