Update Pulp plugin to drop Pulp 2
theforeman/puppet-foreman_proxy pull request #638
Opened 2020-12-16 20:14 UTC by ehelms

Katello 4.0 drops Pulp 2 in favor of Pulp 3 completely. If this
plugin is used, then Pulpcore will be used and the user can decide
if it should be deployed as a mirror configuration or not. This drops
most of the parameters as they are not relevant with Pulp 3.

I was not sure if disabling the Pulp 2 plugins was all that needed doing. At some point we will want to clean them up but figured I'd start by just disabling them. This is obviously backwards incompatible. I prefer to have latest reflect the state of Katello 4.0 given its so different. We could resort to erroring out when a user attempts to use parameters that dont work with 4.0, but that also means we have to keep around a lot this parameter cruft for a lot longer period of time. Further, in the installers use case, this would present misleading parameters.

2020-12-16 20:22 UTC, ekohl requested changes
I don't like it when the software underneath still supports all the functionality. IMHO we should first update the plugin and then update this module to clean out the unused files.

2020-12-16 20:56 UTC, ehelms commented
If we update the plugin first, then we have to, in a coordinated fashion, release a new version of it and update the configuration management layer to prevent breakages. If we update the config management layer to reflect the state we want to be in, then we can more easily remove the old functionality out of the plugin. I am happy to file an issue to track against the plugin for it to get updated, but that should not be a blocker to how we are deploying. Just because some piece of underlying software supports something, does not mean we have to choose to expose it to the user.

2020-12-17 16:03 UTC, ekohl commented
https://github.com/theforeman/smart_proxy_pulp/pull/26 would be the update that drops Pulp 2 on the plugin side.

2020-12-17 16:19 UTC, ehelms commented
I still stand by we can avoid chicken-and-egg, fire off and see if nightly works orchestration, by making this update, turning those plugins off and then having all the code cleaned up. Just because the plugin software supports does not mean our deployment needs to (or should).

2020-12-17 16:32 UTC, ekohl commented
I just have a fundamental issue with this. Essentially this is an anti-feature. It's backwards incompatible anyway, so why not go the whole way and really drop it? I don't want to merge this patch so don't expect an ACK from me.

2020-12-17 16:35 UTC, ehelms commented
I don't mind just dropping it I assume that means removing (https://github.com/theforeman/puppet-foreman_proxy/pull/638/files#diff-8fb2d14548a55c08f905d8327857148fe6c08d960ce0a42703cd99eba72dc2ebR33-R44) and that I would need to add lines to ensure that the configuration files are absent for a release since as far as I can tell nothing cleans those up.

2020-12-17 16:48 UTC, ekohl commented
Correct. See `foreman_proxy::settings_file { 'pulp3':` as an example. This is a side effect of us renaming pulp3 to pulpcore a while back.

2020-12-18 15:08 UTC, ehelms commented
Updated to drop the pulp and pulpnode plugins all together and ensure their settings files are removed.

2021-03-02 00:31 UTC, ekohl requested changes

2021-03-02 00:31 UTC, ekohl commented on manifests/plugin/pulp.pp
> +    },
A shorter way:
```suggestion
    # pulp3: removed in rubygem-smart_proxy_pulp 2.0
    # pulp/pulpnode: removed in rubygem-smart_proxy_pulp 3.0
    foreman_proxy::settings_file { ['pulp3', 'pulp', 'pulpnode']: 
      ensure        => absent,
    },
```

2021-03-02 00:31 UTC, ekohl commented on spec/classes/foreman_proxy__plugin__pulp_spec.rb
> +        it 'should configure pulpnode.yml' do
```suggestion
        it 'should configure pulp.yml' do
```

2021-03-02 00:31 UTC, ekohl commented on spec/classes/foreman_proxy__plugin__pulp_spec.rb
> +	      end
This indenting looks off

2021-03-02 00:31 UTC, ekohl commented on spec/classes/foreman_proxy__plugin__pulp_spec.rb
> +            pulpcore_content_url: 'https://pulpcore.example.com/pulp/content'
It's better to use a trailing comma:
```suggestion
            pulpcore_content_url: 'https://pulpcore.example.com/pulp/content',
```

2021-03-02 00:31 UTC, ekohl commented on templates/plugin/pulp.yml.erb
>  ---
This file can be removed now

2021-03-02 00:31 UTC, ekohl commented on templates/plugin/pulpnode.yml.erb
>  ---
This file can be removed now

2021-03-03 10:39 UTC, ekohl approved these changes
Looks good to me. Let's get a 3.0 release out and packaged in nightly, then merge this.

2021-04-09 12:52 UTC, merged