Release 18.1.0
theforeman/puppet-foreman_proxy pull request #668
Opened 2021-04-28 15:53 UTC by wbclark

I believe this should wait for #666 and #667 to be merged first. @evgeni could you please confirm?

2021-04-28 16:04 UTC, evgeni commented
I don't think we'll get #666 green trivially. And I have expected tests on #667 to fail differently than what they did.

I can spin up a 20.04 box with #667 applied, and if it does what it should we could merge that without the metadata change?

2021-04-29 13:55 UTC, ekohl commented
https://github.com/theforeman/puppet-foreman_proxy/pull/669 should be good and ready to merge.

2021-04-29 15:28 UTC, ekohl requested changes
Please update this with what's currently merged.

2021-04-29 18:56 UTC, wbclark commented
Updated with latest changelogs and new date

2021-04-30 12:48 UTC, ekohl approved these changes

2021-04-30 12:49 UTC, ekohl commented on CHANGELOG.md
> +- Allow puppet-puppet \< 16.0.0 [\#665](https://github.com/theforeman/puppet-foreman_proxy/pull/665) ([wbclark](https://github.com/wbclark))
Feels more like an enhancement to me. Doesn't matter that much since we're doing a minor version bump anyway.

2021-04-30 14:56 UTC, ekohl approved these changes

2021-04-30 15:15 UTC, merged