Release 20.0.0
theforeman/puppet-foreman_proxy pull request #709
Opened 2021-10-24 17:26 UTC by ehelms

Potential release PRs:

- [x] https://github.com/theforeman/puppet-foreman_proxy/pull/708
- [x] https://github.com/theforeman/puppet-foreman_proxy/pull/707
- [x] https://github.com/theforeman/puppet-foreman_proxy/pull/706
- [x] https://github.com/theforeman/puppet-foreman_proxy/pull/687
- [x] https://github.com/theforeman/puppet-foreman_proxy/pull/710
- [x] https://github.com/theforeman/puppet-foreman_proxy/pull/712
- [x] https://github.com/theforeman/puppet-foreman_proxy/pull/713

2021-10-29 18:32 UTC, ekohl commented
Besides the mentioned ones I also want to drop Ubuntu 18.04 support. At least this module already supports 20.04 so that shouldn't be a big deal.

2021-11-02 14:52 UTC, ekohl requested changes
I do think this should become a major version bump. I added the PRs to the TODO list.

2021-11-05 16:56 UTC, ehelms commented
Updated changelog and version for 20.0.0 release

2021-11-05 16:59 UTC, ekohl approved these changes

2021-11-05 18:46 UTC, merged